---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg3
  labels:
    system: pg3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pg3
        system: pg3
    spec:
      containers:
      - name: pg3
        image: healthsamurai/pg3:0.0.1
        imagePullPolicy: Always
