# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-config
# spec:
#   volumes:
#     - name: aidbox-config
#       configMap:
#         name: aidbox-config
#   containers:
#     - name: test-config
#       image: gcr.io/google_containers/busybox
#       command:
#         - top
#       volumeMounts:
#         - name: aidbox-config
#           mountPath: /etc/
#   restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
data:
  postgresql.conf: |
    listen_addresses = '*'
    shared_preload_libraries='pg_pathman'
    synchronous_commit = off
    shared_buffers = '1GB'
    wal_log_hints = on
    wal_level = logical
    max_wal_senders = 30
    max_replication_slots = 30
    max_wal_size = '4GB'
metadata:
  name: aidbox-config
