---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    shared_preload_libraries='pg_pathman'
    synchronous_commit = off
    shared_buffers = '1GB'
    wal_log_hints = on
    port = 5432
    hot_standby = on
    wal_level = logical
    max_replication_slots = 30
    max_wal_size = '4GB'
    archive_mode = on
    archive_command = 'test ! -f /xlog/%f && cp %p /xlog/%f'
    archive_timeout = 10min
    max_wal_size = 1GB
    max_wal_senders = 30
    wal_keep_segments = 100
  pg_hba.conf: |
    local all  all                trust
    host  all  all 127.0.0.1/32   trust
    host  all  all ::1/128        trust
    host  all all all md5
    host  replication postgres 0.0.0.0/0 md5
  .pgpass: |
    db:5432:*:postgres:secret
