apiVersion: v1
kind: Pod
metadata:
  name: db-red
  labels:
    app: db
spec:
  restartPolicy: Never
  volumes:
  - name: db-red-data
    persistentVolumeClaim:
      claimName: db-red-data
  - name: db-red-xlog
    persistentVolumeClaim:
      claimName: db-red-xlog
  - name: db-config
    configMap:
      name: db-config
  containers:
  - name: pg
    volumeMounts:
    - name: db-config
      mountPath: /config/
    - name: db-red-data
      mountPath: /data
      subPath: pgdata
    - name: db-red-xlog
      mountPath: /xlog
      subPath: xlog
    image: aidbox/aidboxdb:passive
    command: ["gosu", "postgres", "postgres", "--config-file=/config/postgresql.conf", "--hba-file=/config/pg_hba.conf"]
