kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aidboxdb-orange-data
  labels:
    app: aidboxdb
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aidboxdb-orange-xlog
  labels:
    app: aidboxdb
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: aidboxdb-orange-init
  labels:
    app: aidboxdb
spec:
  restartPolicy: Never
  volumes:
  - name: aidboxdb-orange-data
    persistentVolumeClaim:
      claimName: aidboxdb-orange-data
  - name: aidboxdb-orange-xlog
    persistentVolumeClaim:
      claimName: aidboxdb-orange-xlog
  - name: aidboxdb-config
    configMap:
      name: aidboxdb-config
  containers:
  - name: pg
    volumeMounts:
    - name: aidboxdb-config
      mountPath: /config/
    - name: aidboxdb-orange-data
      mountPath: /data
      subPath: pgdata
    - name: aidboxdb-orange-xlog
      mountPath: /xlog
      subPath: xlog
    image: aidbox/aidboxdb:passive
    # command:
    #   - "/bin/bash"
    #   - "-c"
    #   - "chmod 0600 /config/.pgpass && chown postgres /config/.pgpass && ls -lah /config/.pgpass && cat /config/.pgpass && su - postgres -c \"cat /config/.pgpass && export PGPASSFILE=/config/.pgpass && export HOME=/config && echo $PGPASSFILE && /pg/bin/pg_basebackup -D /data -Fp -U postgres -w -R -Xs -c fast -l orange -P -v -h aidboxdb\""
    command: ["/bin/bash", "-c", "chown postgres -R /data && chown postgres -R /xlog && chmod 0600 /config/.pgpass && chmod 0700 /data"]

---

apiVersion: v1
kind: Pod
metadata:
  name: aidboxdb-orange
  labels:
    app: aidboxdb
spec:
  restartPolicy: Never
  volumes:
  - name: aidboxdb-orange-data
    persistentVolumeClaim:
      claimName: aidboxdb-orange-data
  - name: aidboxdb-orange-xlog
    persistentVolumeClaim:
      claimName: aidboxdb-orange-xlog
  - name: aidboxdb-config
    configMap:
      name: aidboxdb-config
  containers:
  - name: pg
    volumeMounts:
    - name: aidboxdb-config
      mountPath: /config/
    - name: aidboxdb-orange-data
      mountPath: /data
      subPath: pgdata
    - name: aidboxdb-orange-xlog
      mountPath: /xlog
      subPath: xlog
    image: aidbox/aidboxdb:passive
    command:
      - "gosu"
      - "postgres"
      - "bash"
      - "-c"
      - "echo \"primary_slot_name = 'orange'\" >> /data/recovery.conf && echo \"standby_mode = 'on'\" >> /data/recovery.conf && postgres --config-file=/config/postgresql.conf --hba-file=/config/pg_hba.conf"
