kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aidbox-red-data
  labels:
    app: aidbox
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: aidbox-red
  labels:
    app: aidbox
spec:
  terminationGracePeriodSeconds: 10
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - aidbox
          topologyKey: kubernetes.io/hostname
  volumes:
  - name: aidbox-red-data
    persistentVolumeClaim:
      claimName: aidbox-red-data
  containers:
  - name: pg
    image: aidbox/aidboxdb:0.0.1-alpha6
    ports:
    - containerPort: 5432
      name: pg
    env:
    - name: PGUSER
      value: postgres
    - name: POSTGRES_DB
      value: aidbox 
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: PG_ROLE
      value: replica
    - name: PG_MASTER_HOST
      value: aidbox.pg3 
    - name: PG_REPLICA
      value: red
    livenessProbe:
      exec:
        command:
        - psql
        - -c
        - select 1
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: aidbox-red-data
      mountPath: /data
      subPath: pgdata
