---
apiVersion: v1
kind: Secret
metadata:
  name: pg3-controller-secrets
  namespace: pg3-controller
type: Opaque
data:
  KUBE_TOKEN:
  KUBE_URL:
  TELEGRAM_TOKEN:
  TELEGRAM_CHATID:
  NOTIFICATION_ENABLED: false
